# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: gostt-writer
    main: ./cmd/gostt-writer
    binary: gostt-writer
    goos: [darwin]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -extldflags '-framework Foundation -framework Metal -framework MetalKit -framework CoreML -lggml-metal -lggml-blas'

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - config.example.yaml

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: chaz8081
    name: gostt-writer
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"
